### PR TITLE
Fix Bootstrap 4 field error classes

### PR DESCRIPTION
**Pull request by graystevens**
Ref #732

### CODE REVIEW

**Comment by carltongibson** [comment]
@graystevens This looks good. Two things: 

1. Tests need adjusting. 
2. Can you just link to the BS4 docs so I can verify the change. 

Thanks for the input! 👍

**Comment by gnzgo** [comment]
For what it's worth, I've just tested the changes and it works perfectly

**Comment by graystevens** [comment]
Thanks @zoidbergwill, I wasn't going to get the time until much later to look at the tests.

**Comment by zoidbergwill** [comment]
@graystevens Awesome. No worries. Hopefully that sorts them out. Thanks for your contribution. 🙏 

@carltongibson I find this mention to it and it being used a bunch on this page: [Server side validation](https://getbootstrap.com/docs/4.0/components/forms/#server-side)

Sucks that it isn't in the migration guide [here](https://getbootstrap.com/docs/4.0/migration/)

**Comment by carltongibson** [comment]
Excellent. Thanks everybody for this!

@zoidbergwill I'm happy to take your lead on the BS4 stuff — you know it **much** better than I do. (without input I'm not at all sure when we can say "Finished").

**Pull request merged**
