### PR TITLE
1.9.0 release

### PR DESCRIPTION
**Pull request by smithdc1**
Let's use this to manage & discuss the next release. Below are my thoughts. 

I've updated the milestones for the pull requests which I think should be merged ahead of the next release. They are mostly about removing support for old versions and adding support for future versions of Django. More could make it into the next release but I've tried to keep that list to 'must have'.

To do list
- [x] #947 review and merge
- [x] Review docs / release notes etc. Have we been clear enough that we're dropping support for old versions, have changes been captured in all the right places

### CODE REVIEW

**Comment by smithdc1** [comment]
Hi @carltongibson @bryan-brancotte 

Hope you are both well. 

I think we're nearly there with a 1.9.0 release. One remaining pull request that I think we should include in the next release which allows support with the next release of Django. 

Bryan - do you have availability to publish the next release once we're all happy?

**Comment by bryan-brancotte** [comment]
Hi @smithdc1 

I see that good work have been done ! Yes I can publish when you are ok with the release, but feel free to do it if you want to.

Best

**Comment by smithdc1** [comment]
ok- all ready to be published tomorrow. 🚀 

Whilst this is a fairly small release for users (mainly removal of support for old versions) the underlying code base has changed a fair bit as it now 'compatible' with Black, isort and Flake8!

**Comment by smithdc1** [comment]
@carltongibson help please! 

I'm getting an error uploading to PyPI. Can you check my access rights? I don't see django-crispy-forms under my projects.

Thanks!

**Comment by carltongibson** [comment]
Hi @smithdc1. Argh, I didn't add you yet. Double-check you're https://pypi.org/user/smithdc1/ on PyPI?

**Comment by smithdc1** [comment]
Hi @carltongibson


Yes this is me and I have 2fa enabled. 😀
https://pypi.org/user/smithdc1/

Thanks

**Comment by carltongibson** [comment]
Right, you're in. Sorry. 😊

**Comment by smithdc1** [comment]
All done! 🎉 

[PyPI](https://pypi.org/project/django-crispy-forms/1.9.0/) ✔️ 
[Docs](https://django-crispy-forms.readthedocs.io/en/1.9.0/) ✔️ 
[GitHub Release](https://github.com/django-crispy-forms/django-crispy-forms/releases/tag/1.9.0) ✔️

**Comment by bryan-brancotte** [comment]
:clap: @smithdc1

**Pull request merged**
