### PR TITLE
[compat] Remove python 2.7 support deprecated beginning of 2020

### PR DESCRIPTION
**Pull request by Djailla**

### CODE REVIEW

**Comment by bryan-brancotte** [comment]
duplicates of #912 ?

**Comment by Djailla** [comment]
@bryan-brancotte ah yes, but mine pass the CI ;)

**Comment by Djailla** [comment]
@bryan-brancotte and I did not even saw #940 
Do you want me to close this PR ?

**Comment by bryan-brancotte** [comment]
Hi @Djailla 
#946 and #912 both pass the CI now, as they are very similar maybe you can contribute to the existing PR ? #912 have the anteriority.
Best regards

**Pull request closed without merging**
