### PR TITLE
Update Bootstrap 4 accordion and accordion group

### PR DESCRIPTION
**Pull request by jhotujec**
This fixes `Bootstrap 4` HTML for accordion and accordion group in `django-crispy-forms`

### CODE REVIEW

**Comment by zoidbergwill** [comment]
Hi there, @jhotujec 

Thanks for the contribution! This looks good to me.

Would you be willing to take a look at [fixing the tests](https://travis-ci.org/django-crispy-forms/django-crispy-forms/jobs/302684407)?

I'd love to test all of these layout objects in [crispy-test-project](https://github.com/django-crispy-forms/crispy-test-project) so we could easily catch these regressions.

**Comment by Exelscior** [comment]
Any news on when these fixes will be packaged on pypi by any chance?
Atm having to pip install from github master repo is an issue for many.

And thanks @jhotujec for the fix.

**Comment by carltongibson** [comment]
@Exelscior [Pip's VCS support is first class](https://pip.pypa.io/en/stable/reference/pip_install/#git) — it's not to be avoided. There's no reason for it to be an "issue". (Hint: just use it.) 

We have a few raining small issues for BS4. It'll be nice to have those in so we can wrap up it up.

**Comment by Exelscior** [comment]
@carltongibson Oh I perfectly agree with you there, just I work in a department where deploying on OpenNebula VMs have restricted network access. So github.com for example is blocked (with a real bureaucratic hastle to get it changed...). It took a while to get pypi indexes authorized, and I know this is common in the industry.

Thanks for the reply and info in anycase. :+1:

**Comment by carltongibson** [comment]
@Exelscior: I can't believe anyone working in such an environment can be in such a rush. 🙂

**Pull request merged**
