### PR TITLE
Updated test settings

### PR DESCRIPTION
**Pull request by michael-k**
Tests are failing for `Django==1.11.1`, they passed with `1.11b1`.

### CODE REVIEW

**Comment by carltongibson** [comment]
@michael-k Good one. Yes. Time for a release I think 👍

**Comment by carltongibson** [comment]
I guess the failures are related to #683... — but I'm not sure exactly where the change came in.

**Comment by carltongibson** [comment]
Strings were updated in Django https://github.com/django/django/commit/afe4edb4eaaad89acefa6b6d0697d6fa67387eea#diff-93bb3cf50e3bdd0ef0baa77c618ca596L298

> Updated core translations from Transifex
> Forward port of 96ec72e from stable/1.11.x

**Comment by michael-k** [comment]
@carltongibson I've updated the PR

**Comment by carltongibson** [comment]
@michael-k Thanks for this.

**Pull request merged**
