### PR TITLE
Remove Python 2 support

### PR DESCRIPTION
**Pull request by smithdc1**
This PR removes support for python 2. 

1) Update tox.ini and travis.yml to stop testing for python 2
2) removal of python 2 in compatibility.py, and put python 3 commands into individual files
3) removal of izip in crispy_forms_field
4) added to change log (I've not change the readme file, so this still refers to python 2 (v1.8 supports python 2). We will need to change this at some point.

Looking forward to the review and feedback.

### CODE REVIEW

**Comment by bryan-brancotte** [comment]
Hi @smithdc1 

I am very surprised that the tests passed as some import were missing maybe the force push wronly validated the tests ? Otherwise the PR looks fine to me, so waiting for the CI.

**Comment by smithdc1** [comment]
@bryan-brancotte thanks for the review. I fixed the failing test 😄.

No that it matters (yet?) but django latest is failing (I'll take a quick look) 🔬

**Comment by smithdc1** [comment]
Yes, we will need to update the tests due to changes in django latest.

This commit tidied up some backwards compatibility imports which we were using. 
 
https://github.com/django/django/commit/129583a0d3cf69b08d058cd751d777588801b7ad#diff-7a3347e3650b9f77b33b71f753d73751

I'll raise a new PR.

**Comment by smithdc1** [comment]
Hi @bryan-brancotte I've rebased this to remove the merge conflicts.

**Comment by smithdc1** [comment]
@bryan-brancotte happy new year! Hope you had a good break. :tada: 

Are you happy for this to be merged?

**Comment by smithdc1** [comment]
Thanks @carltongibson . Happy New Year to you.

**Comment by carltongibson** [comment]
💃

**Comment by bryan-brancotte** [comment]
Happy new years to you both !
I just came back from my break, but I'm glade this PR went well @smithdc1 !

**Pull request merged**
