### PR TITLE
Remove the function `copy_context`

### PR DESCRIPTION
**Pull request by illia-v**

### CODE REVIEW

**Comment by carltongibson** [comment]
@illia-v Could you rebase this please. (It's great.)

**Comment by carltongibson** [comment]
@illia-v You seem to have force pushed a bad commit...?

**Comment by illia-v** [comment]
@carltongibson seems OK now. Should I squash that two commits?

**Comment by carltongibson** [comment]
Good work. Thanks! 

(GitHub did the squash.)

**Pull request merged**
