### PR TITLE
Fix formactions for horizontal forms

### PR DESCRIPTION
**Pull request by pascalfree**
Related:
https://github.com/django-crispy-forms/django-crispy-forms/pull/919
https://github.com/django-crispy-forms/django-crispy-forms/issues/805#issuecomment-379343007

### CODE REVIEW

**Comment by smithdc1** [comment]
Hi @pascalfree thanks for the pull request! 👍 

This looks good to me. @bryan-brancotte anything to add?

**Comment by monim67** [comment]
Please merge this PR for the next release. The removal of `row` class has affected me too, running with a temporary patch now.

**Comment by bryan-brancotte** [comment]
before
Capture d’écran de 2020-03-19 11-30-33

With #977
Capture d’écran de 2020-03-19 11-30-42

**Review by bryan-brancotte — COMMENTED** [review]
##

**Review by bryan-brancotte — APPROVED** [review]
Ok for me ! Thanks for the PR !

**Pull request merged**
