### PR TITLE
CSS class for input group size in Bootstrap 4

### LINKED ISSUE #1071: Allow to choose size of input group in Bootstrap 4
* Package version: 1.9.2
* Django version: 3.1.2
* Python version: 3.8.5
* Template pack: (Optional)

### Description:

Currently, it's not possible to set the size of a Bootstrap Input group without overwriting the template.

According to the [Bootstrap documentation](https://getbootstrap.com/docs/4.5/components/input-group/#sizing) a class `input-group-sm` or `input-group-lg` must be added to the element that has the class `input-goup`.
Unfortunately, this is not possible as the [class there in the template is hardcoded](https://github.com/django-crispy-forms/django-crispy-forms/blob/2f1ad1fff035ef1906dfa012e42ac042465af22b/crispy_forms/templates/bootstrap4/layout/field_with_buttons.html#L11).

### Solution:

We could reuse the `input-size` field as it is in the [wrong place anyway](https://github.com/django-crispy-forms/django-crispy-forms/blob/2f1ad1fff035ef1906dfa012e42ac042465af22b/crispy_forms/templates/bootstrap4/layout/field_with_buttons.html#L13). At the same time [`PrependedAppendedText`](https://github.com/django-crispy-forms/django-crispy-forms/blob/6c0ffe2f417bdd6463d87905844ddb86b112cc96/crispy_forms/bootstrap.py#L23) could be fixed as `input-lg` and `input-sm` only seems to be available in Bootstrap 3 and not Bootstrap 4.

### PR DESCRIPTION
**Pull request by medihack**
There is no `input-sm` and `input-lg` CSS class in Bootstrap 4. It uses several other classes to adjust the size in form controls (`form-control-sm`, `form-control-lg`, `custom-select-sm`, `custom-select-lg`, `input-group-sm`, `input-group-lg`). For input groups it is `input-group-sm` and `input-group-lg` (but together with the `input-group` class)`.

Fixes #1071

### CODE REVIEW

**Comment by smithdc1** [comment]
Hi @medihack thanks for this. I hope to look at this in the coming days. 

Once we've got this in I think it's time to start considering the next release.

**Comment by smithdc1** [comment]
Thanks for this. :+1:

I think we should also document how to change the input size somewhere, this seems like an undocumented feature to me at the moment. What do you think?

https://django-crispy-forms.readthedocs.io/en/latest/layouts.html?highlight=input%20size#bootstrap-layout-objects

**Comment by medihack** [comment]
> 
> 
> Thanks for this. +1
> 
> I think we should also document how to change the input size somewhere, this seems like an undocumented feature to me at the moment. What do you think?
> 
> https://django-crispy-forms.readthedocs.io/en/latest/layouts.html?highlight=input%20size#bootstrap-layout-objects

Sure, I will look into it at the weekend.

**Comment by medihack** [comment]
Hmm, couldn't think of a better way to document it. Just added another bullet point.

**Comment by smithdc1** [comment]
Hi @medihack thansk for your efforts here.

How about we move your new docs to the bottom and link to it from the appropriate inputs? What do you think? (I'm sure there is a better way to format the link but I stuggle with Sphinx a little).

@cpina appreciate your views here.

``` rst
diff --git a/docs/layouts.rst b/docs/layouts.rst
index 5135aca..93b765c 100644
--- a/docs/layouts.rst
+++ b/docs/layouts.rst
@@ -205,7 +205,7 @@ These ones live under module ``crispy_forms.bootstrap``.
 .. image:: images/form_actions.png
    :align: center
 
-- **AppendedText**: It renders a bootstrap appended text input. The first parameter is the name of the field to add appended text to, then the appended text which can be HTML like. There is an optional parameter ``active``, by default set to ``False``, that you can set to a boolean to render appended text active::
+- **AppendedText**: It renders a bootstrap appended text input. The first parameter is the name of the field to add appended text to, then the appended text which can be HTML like. There is an optional parameter ``active``, by default set to ``False``, that you can set to a boolean to render appended text active. Accepts the `input_size`_ argument::
 
....

-- **PrependedText**: It renders a bootstrap prepended text input. The first parameter is the name of the field to add prepended text to, then the prepended text which can be HTML like. There is an optional parameter ``active``, by default set to ``False``, that you can set to a boolean to render prepended text active::
+- **PrependedText**: It renders a bootstrap prepended text input. The first parameter is the name of the field to add prepended text to, then the prepended text which can be HTML like. There is an optional parameter ``active``, by default set to ``False``, that you can set to a boolean to render prepended text active. Accepts the `input_size`_ argument::
 
.....
 
-- **PrependedAppendedText**: It renders a combined prepended and appended text. The first parameter is the name of the field, then the prepended text and finally the appended text::
+- **PrependedAppendedText**: It renders a combined prepended and appended text. The first parameter is the name of the field, then the prepended text and finally the appended text. Accepts the `input_size`_ argument::
 
....
 
-- **FieldWithButtons**: You can create an input connected with buttons::
+- **FieldWithButtons**: You can create an input connected with buttons. Accepts the `input_size`_ argument::
 
....
 
+.. _`input_size`:
+
+Input group size
+----------------
+
+**Input group size**: Adjust the size of an input group (``FieldWithButtons``, ``AppendedText``, ``PrependedText``, ``PrependedAppendedText``) with the appropriate CSS class, e.g. ::
+
+    # Bootstrap 3
+    FieldWithButton('field_name', StrictButton("Go!"), input_size="input-sm")
+    FieldWithButton('field_name', StrictButton("Go!"), input_size="input-lg")
+
+    # Bootstrap 4
+    FieldWithButton('field_name', StrictButton("Go!"), input_size="input-group-sm")
+    FieldWithButton('field_name', StrictButton("Go!"), input_size="input-group-lg")
+
 .. _`override templates`:
 
 Overriding layout objects templates
-- 
2.20.1

```

**Comment by cpina** [comment]
Thanks very much @medihack : super clear explanations on the ticket and the PR that helped me to understand it.

For the `Appended` and `Prepended` text: I need to use `css_class` to change the size instead of `input_size` because of this code: https://github.com/django-crispy-forms/django-crispy-forms/pull/1080/commits/3ffc9d07d0c4ca89f39f8010806a8ced56293748#diff-8a8e322dd3473c88fe604b7dc4785b788587311a4f54d54644e6da26c19b5fe4R22 - let me know if I'm not looking at the most updated files please.

I guess that it makes sense to use `input_size` instead of `css_class` but I might need to think a bit more.

For the `FieldWithButtons`: I couldn't make it work as the PR is now. I've tested a fix but I'm not sure if you had this in mind or it was a problem between my chair and my screen :-) I could make it work if I changed FieldWithButtons.__init__(), save in `self._input_size` the `input_size` (similar to the `PrependedAppendedText.init()` code) and in FieldWithButtons.render add this `input_size` in `extra_content`. Basically:
https://github.com/cpina/django-crispy-forms/commit/a664a991e1091633f84924b3594056405885a969

(this needs refactoring if it was the way to go)

Did I miss-use how it was supposed to be used?

Thanks again for this PR, almost there I think :-)

**Comment by smithdc1** [comment]
https://github.com/django-crispy-forms/django-crispy-forms/pull/1114 contained most of the changes here and #1159 addresses the remaining part of this PR. @medihack thanks for everything you've done here. 🙏

**Pull request closed without merging**
