### PR TITLE
Add Grouped choices support in bootstrap4 for CheckboxesSelectMultiple

### PR DESCRIPTION
**Pull request by rogeremasse**
Honor cols Field keyword arg when rendering CheckboxesSelectMultiple.

### CODE REVIEW

**Comment by rogeremasse** [comment]
Sorry this PR is not really a complete bug fix. There are no tests. There is no support for anything but bootstrap4. The 3 templates I created could probably be combined into checkboxselectmultiple.html but I'm not sure the result would be very easy to read... so I left it as separate templates. Since you asked for help, I thought my patch might be useful for someone.

**Comment by rogeremasse** [comment]
@carltongibson  Nice chatting with you during the hallway track at DjangoCon. Thank you for speaking with me about my PR.

**Comment by carltongibson** [comment]
Hey @rogeremasse. No problem! Thanks again for your input! (Do you want to join as a contributor?)


@bryan-brancotte Can I ask you to have a look here and discuss? 

(I'm happy to input on details, but first step is does this look right for Bootstrap 4?)

**Comment by rogeremasse** [comment]
Hello @carltongibson I would be honored to join as a contributor and I agree with your suggested first step.

**Comment by bryan-brancotte** [comment]
Dear @rogeremasse 

A little late but thanks for the PR, the support of grouped checkboxes is indeed needed (also absente in bootstrap3 though).

They have been some update recently, inclusing in checkboxselectmultiple (cf #899) would you mind updating your PR from the master ? Also could you provide instruction on reproducing `cols=2` from https://github.com/django-crispy-forms/django-crispy-forms/pull/813#issuecomment-390347588

Thanks again for the PR

**Comment by smithdc1** [comment]
Closed in favour or #1155

**Pull request closed without merging**
