### PR TITLE
Tailwind support!

### PR DESCRIPTION
**Pull request by smithdc1**
Hi @carltongibson @bryan-brancotte 

Hope you are both well. 

Time for a bit of show and tell. 👀 

Once you've read the below I'm interested in your view on the following:

- API design - how can it be improved
- Is this idea worth progressing further (a quick google doesn't show anyone else with a template pack)
- Thoughts on next steps, how would we progress. (I think let's agree the API, and ship it. We would never spot/fix bugs unless it gets used)
- Crispy-Forms vs new package (my view is the latter, but there are options here)
- Suspect I need to go and fix a couple of the standard tests... the ones which count inputs are bound to fail....

I've had a go at trying to add support for Tailwind. Tailwind as a utlity first framework doesn't have pre-built form layouts we can copy. Further I feel that taking an opinion is against the point of it being utility first. 

I've therefore created a new class to use as a data store for the css classes. The templates then access these and add them where needed. This is the first time I've created an API like this so I'd really value any feedback. It works something like this. 

```
# pass in a dictionary with a style for each input type
style = {"text": "mb-2 text-red-600"}
css_container = CSSContainer(style)
css_container
Out[10]: {'text': 'text-red-600 mb-2', 'number': '', 'email': '', 'url': '', 'password': '', 'hidden': '', 'multiplehidden': '', 'file': '', 'clearablefile': '', 'textarea': '', 'date': '', 'datetime': '', 'time': '', 'checkbox': '', 'select': '', 'nullbooleanselect': '', 'selectmultiple': '', 'radioselect': '', 'checkboxselectmultiple': '', 'multi': '', 'splitdatetime': '', 'splithiddendatetime': '', 'selectdate': ''}
# this could get a bit long winded, so let's fast track and add a base style to all input types
base_style = {"base": "apply to all"}
css_container = CSSContainer(base_style)
css_container
Out[13]: {'text': 'apply to all', 'number': 'apply to all', 'email': 'apply to all', 'url': 'apply to all', 'password': 'apply to all', 'hidden': 'apply to all', 'multiplehidden': 'apply to all', 'file': 'apply to all', 'clearablefile': 'apply to all', 'textarea': 'apply to all', 'date': 'apply to all', 'datetime': 'apply to all', 'time': 'apply to all', 'checkbox': 'apply to all', 'select': 'apply to all', 'nullbooleanselect': 'apply to all', 'selectmultiple': 'apply to all', 'radioselect': 'apply to all', 'checkboxselectmultiple': 'apply to all', 'multi': 'apply to all', 'splitdatetime': 'apply to all', 'splithiddendatetime': 'apply to all', 'selectdate': 'apply to all'}
# now we can update as we go
css_container.text = ""
css_container
Out[22]: {'text': '', 'number': 'apply to all', 'email': 'apply to all', 'url': 'apply to all', 'password': 'apply to all', 'hidden': 'apply to all', 'multiplehidden': 'apply to all', 'file': 'apply to all', 'clearablefile': 'apply to all', 'textarea': 'apply to all', 'date': 'apply to all', 'datetime': 'apply to all', 'time': 'apply to all', 'checkbox': 'apply to all', 'select': 'apply to all', 'nullbooleanselect': 'apply to all', 'selectmultiple': 'apply to all', 'radioselect': 'apply to all', 'checkboxselectmultiple': 'apply to all', 'multi': 'apply to all', 'splitdatetime': 'apply to all', 'splithiddendatetime': 'apply to all', 'selectdate': 'apply to all'}
# can add and remove as well
css_container += style
css_container
Out[24]: {'text': 'text-red-600 mb-2', 'number': 'apply to all', 'email': 'apply to all', 'url': 'apply to all', 'password': 'apply to all', 'hidden': 'apply to all', 'multiplehidden': 'apply to all', 'file': 'apply to all', 'clearablefile': 'apply to all', 'textarea': 'apply to all', 'date': 'apply to all', 'datetime': 'apply to all', 'time': 'apply to all', 'checkbox': 'apply to all', 'select': 'apply to all', 'nullbooleanselect': 'apply to all', 'selectmultiple': 'apply to all', 'radioselect': 'apply to all', 'checkboxselectmultiple': 'apply to all', 'multi': 'apply to all', 'splitdatetime': 'apply to all', 'splithiddendatetime': 'apply to all', 'selectdate': 'apply to all'}
remove_style = {"text": "mb-2"}
css_container -= remove_style
css_container
Out[31]: {'text': 'text-red-600', 'number': 'apply to all', 'email': 'apply to all', 'url': 'apply to all', 'password': 'apply to all', 'hidden': 'apply to all', 'multiplehidden': 'apply to all', 'file': 'apply to all', 'clearablefile': 'apply to all', 'textarea': 'apply to all', 'date': 'apply to all', 'datetime': 'apply to all', 'time': 'apply to all', 'checkbox': 'apply to all', 'select': 'apply to all', 'nullbooleanselect': 'apply to all', 'selectmultiple': 'apply to all', 'radioselect': 'apply to all', 'checkboxselectmultiple': 'apply to all', 'multi': 'apply to all', 'splitdatetime': 'apply to all', 'splithiddendatetime': 'apply to all', 'selectdate': 'apply to all'}

```
In addition there is a "option_label" that can be passed in to style radio / checkbox input labels. Input labels are styled using existing functionality. 

I've also built out a template using crispy-test-project (although I've just realised I've broken master as it needs this PR to work, sorry.)

Here is the image. 

screencapture-127-0-0-1-8000-tailwind-2020-04-21-20_56_13

Looking forward to hearing from you.

### CODE REVIEW

**Comment by smithdc1** [comment]
Hi @carltongibson 

Thanks for your comments. To clarify a couple of points, if I may. 

> I've played with a Tailwind plugin for Django forms, so people don't have to jump all the way into, say, crispy in order to render a straight-forward form nicely. That could be something a crispy-tailwind pack shipped. (I had tailwind components scoped under a single class on the form.)

If I explored providing an opinionated output that looked 'ok' (something like the above image) whereby someone could use {{ my_form|crispy }} and have a reasonable looking form; they would not need to setup helper, layout, design all the css properties etc. Would that meet this requirement? 

There is also a slightly deeper question on what to do with radio / checkbox. I see there are custom css items available.... do we try and ship that too!? Longer term could also give an opinion on prepend / postpend input boxes too.... 

I think that adding this to core doesn't make sense when our strategic aim is the exact opposite. I'll therefore set the up as a new repo. Would you be ok with me adding it under the "django-crispy-forms" org?

**Comment by carltongibson** [comment]
HI @smithdc1 

> Would that meet this requirement?

My plugin just took a regular form, so not even `|crispy`, using `as_p()` but... 🤷 

> Would you be ok with me adding it under the "django-crispy-forms" org?

Yeah, do. That'll be cool. (Let me know if there's permissions issues or anything...)

**Comment by bittermandel** [comment]
@smithdc1 I'd be happy to help out and be an early user of this!

**Comment by smithdc1** [comment]
@bittermandel super - let me do some basic setup and I'll be in touch. 👍

**Comment by smithdc1** [comment]
Closing this PR as it we will develop through a separate package.

**Pull request closed without merging**
