### PR TITLE
Fixes documentation: uses right 'load' in the template

### PR DESCRIPTION
**Pull request by cpina**

### CODE REVIEW

**Comment by cpina** [comment]
I'll close and open the PR to force the tests to run again -one failed with a timeout not relevant to the changed documentation

**Comment by smithdc1** [comment]
Hey @cpina :wave:

Thanks for the pull request. 

Yes I tried to re-run tests also. Seems to be a codecov bandwidth issue. Unrelated to the change anyway.

I'm going to have to sleep on this one. The current approach works, in fact we import the filter in the tags file so it does. It's also been like this for a long time.

I think it's a philosophical question about _why_ we do it like this (looks like a very deliberate decision). May need to wait a little while and see if anyone else has any thoughts, or see if I can dig through the commit history. 

Take care.

**Comment by smithdc1** [comment]
@cpina hey, we should revisit this. 🙂

If you are happy then please go ahead and merge.

**Comment by cpina** [comment]
I've done some investigation: do not merge this PR :-) (actually we might want to close it)

I think that in May when I opened it: I was using PyCharm and I followed the django-crispy-forms instructions and I did this:
```html
{% load crispy_forms_tags %}

{{ myform|crispy }}
```

And PyCharm highlighted `crispy` as warning of undefined template tag. Then I changed without looking much into the django-crispy-forms code the the load line to `{% load crispy_forms_filter %}` and both PyCharm and Django were happy.

The change is not needed and without the change it works because in the `crispy_forms_tags.py` there is an import of the functions that are in the `crispy_forms_filter.py`: https://github.com/django-crispy-forms/django-crispy-forms/blob/master/crispy_forms/templatetags/crispy_forms_tags.py#L13

As a django-crispy-forms user I might not need to know where the tags are defined and having as a entry gate only `crispy_forms_tag` seems like a valid approach.

I've prepared a small test case and a ticket with PyCharm/IntelliJ:
 * Test case: https://github.com/cpina/django_pycharm_import_templates
 * PyCharm ticket: https://youtrack.jetbrains.com/issue/PY-45810

**Comment by smithdc1** [comment]
wow, great work :bow:

**Comment by carltongibson** [comment]
So... 😀

I don't suppose it matters ultimately but I'd say the idea was to just have one entry point to the template tags (and filters). 

Maybe names could be better or docs could be better but I don't think I'd change that. 

Could we adjust the imports to keep the IDEs happy? 🤔 

I'd say close this.

**Comment by cpina** [comment]
@carltongibson : yesterday I tried to adjust the import, specially replacing this line: https://github.com/django-crispy-forms/django-crispy-forms/blob/master/crispy_forms/templatetags/crispy_forms_tags.py#L13 by an explicit list of functions to import. I was hoping that PyCharm (in my case) would find it. I didn't succeed this way but if IntelliJ suggest something I'll report here.

I have another idea that I'll try later.

**Comment by cpina** [comment]
A possible workaround: https://github.com/cpina/django_pycharm_import_templates/commit/7b4b63191278ff56a8570a89c91132baa8203237

If we did above approach on django-crispy-forms: a unit test to check that the functions with decorators defined in `crispy_forms_filter.py` are defined with the same decorator in `crispy_forms_tag.py` would be good.

If anyone had any other idea let me know and I'm happy to try it with PyCharm. Otherwise waiting for PyCharm support to answer the ticket might be ok for some time.

**Pull request closed without merging**
