### PR TITLE
Version 1.8.1

### PR DESCRIPTION
**Pull request by bryan-brancotte**

### CODE REVIEW

**Comment by smithdc1** [comment]
Hi Bryan,

Thanks for pulling his together. My comments:

- should we update the docs version? https://github.com/django-crispy-forms/django-crispy-forms/blob/863c7f8e65cfb94a0e05c385312c197d5e7eedb8/docs/conf.py#L56

- should we signpost the impact use_custom_control now has on the file field in the change log, and that the required js is now included? An old issue on style of the file filed is one of the most viewed pages, so something people are interested in or is a feature we need to communicate better on?
https://github.com/django-crispy-forms/django-crispy-forms/graphs/traffic

- should we do anything to thank people who have made commits to this version as I think we've had some new contributors?. Carlton, anything that Django does that we could replicate?

**Comment by bryan-brancotte** [comment]
Hi David

* docs version updated
* Thanks for pointing that the docs needed update, indeed now the JS is embeded !
* I let @carltongibson address the last point

Best wishes !

**Comment by carltongibson** [comment]
Errr... Happy if you want to call out anybody in particular. (On Django we often put a thanks in the commit message...)

**Comment by smithdc1** [comment]
@bryan-brancotte I'm happy with this. :ok_hand: 
Good luck with the next stage!

**Pull request merged**
