### PR TITLE
Add missing classifiers in setup.py

### PR DESCRIPTION
**Pull request by ad-m**

### CODE REVIEW

**Comment by carltongibson** [comment]
I'm not sure I want to add this. We follow Django's supported versions. Adding what we support here just adds to the maintenance. It's just one more thing to keep in sync.

**Comment by ad-m** [comment]
Adding missing classifiers will make it easier to find your project, such as https://pypi.org/search/?c=Framework+%3A%3A+Django+%3A%3A+1.11. On this page, searching without defining the Django version often leads to outdated libraries.

**Comment by carltongibson** [comment]
OK but then I think we need to script updating these in all places where they appear, so we only need to maintain the list in one location

**Comment by zoidbergwill** [comment]
Scripting or making it easy, even with just reminders pointing to the other places, would be awesome , for Python and Django versions.

**Comment by ad-m** [comment]
@carltongibson , we can add warning if installed on unsupported django version and change warning into errors on CI (```-W```)?

**Comment by carltongibson** [comment]
@ad-m My worry here is that the list of classifiers becomes just one more thing to keep on top of. I

Ideally we maintain the supported Django versions in one place, the tox config. We already have that duplicated for travis. (We should update that.) 

I'm not convinced the benefits outweigh the extra hassle here. I am happy to add it if it's scripted though. (Read from tox.ini, update `setup.py` to match.)

**Comment by carltongibson** [comment]
I'm going to say no to this right now. We'll be updating for Django 2.0. Maybe we can add these after that.

**Pull request closed without merging**
