### PR TITLE
issue #1035: disable radio select when field is disabled

### PR DESCRIPTION
**Pull request by kverdecia**

### CODE REVIEW

**Comment by smithdc1** [comment]
@kverdecia super, thanks for this 🙏 

Before I merged I wondered if you be in the market for making the same change to `checkboxselectmultiple.html`?

**Comment by kverdecia** [comment]
Sure, I'll check the template in a few hours

**Comment by kverdecia** [comment]
Hi David, I've just made the change for the checkbox templates

**Comment by smithdc1** [comment]
This is great, thank you. 👍

**Comment by kverdecia** [comment]
Great

**Pull request merged**
