### PR TITLE
[WIP] don't add 'form-control' class to multi value fields

### PR DESCRIPTION
**Pull request by foobacca**
the field might contain checkboxes, and we wouldn't want to add the
form-control class to checkboxes, so it is not safe to add the class to
multi value fields.

### CODE REVIEW

**Comment by foobacca** [comment]
This is one possible fix for issue #560.

To complete it, I need to:

* add tests for is_multivalue as a filter
* add the filter is_multivalue to the docs

but I thought I'd put the core up early for feedback.

**Comment by foobacca** [comment]
Having said:

> * add tests for is_multivalue as a filter
> * add the filter is_multivalue to the docs

I can't find tests or docs for is_checkbox and the other similar filters.  So maybe there is a bigger issue here.  Any guidance appreciated.

**Comment by carltongibson** [comment]
@foobacca Thanks for the input here. 

First off: grrrr, grimble, grrr... special cases... :-) — It looks right, if that's that approach. Let me have a little think (but otherwise I think we'll go for this.)

**Comment by carltongibson** [comment]
Superseded by #694

**Pull request closed without merging**
