### PR TITLE
Removed Bootstrap3 Template Pack

### PR DESCRIPTION
**Pull request by smithdc1**
Maybe more of the tests could go at this point. I'm sure many of them are just asserting HTML where that now sits with the template packs. However, I think it's wise for that to be part of a follow up PR.

### CODE REVIEW

**Review by carltongibson — COMMENTED** [review]
This is great work! 🎁

**Comment by smithdc1** [comment]
Thank you -- finally getting some breathing room to push a few things forward.

I think we are near the point where I can release 2 alpha and ask for feedback from the community. (next year 🎄 🎅  )

**Comment by carltongibson** [comment]
I think it's really quite exciting. Combined with the changes in Django itself, separating the template packs gives room for crispy to change and grow, or feed back into core, as appropriate. Thank you for your effort here! 

Have a good Christmas! 🎁

**Comment by smithdc1** [comment]
The package is now published, so I can move forward with this. 

https://pypi.org/project/crispy-bootstrap3/2022.1/

**Pull request merged**
