### PR TITLE
Support Django 2.2 and Python 3.7

### PR DESCRIPTION
**Pull request by johnthagen**

### CODE REVIEW

**Comment by carltongibson** [comment]
Hi @johnthagen This is great, except the `detox` tool we were using recently broke. Can you drop it as per this change on Django-filter here. Then this'll pass 🤞. 

Also, happy to pull #866 in here too.

**Comment by carltongibson** [comment]
So the parallel change would be here: 

https://github.com/django-crispy-forms/django-crispy-forms/blob/cd476927a756133c667c199bb12120f877bf6b7e/.travis.yml#L14-L19

**Comment by johnthagen** [comment]
> Can you drop it as per this change on Django-filter here

Did you happen to miss a link?

**Comment by carltongibson** [comment]
Oops. Yes I did. Hang on...

**Comment by carltongibson** [comment]
Here you go https://github.com/carltongibson/django-filter/pull/996

**Comment by johnthagen** [comment]
@carltongibson I got this PR as far as I could, but I don't have much insight into why tests are failing. Feel free to push to this PR to fix those issues. The other tox/pytest/travis stuff should be correct now.

I think what might be going on is that I needed to bump to `xenial` which may have a newer version of pytest than `trusty`. You might want to explicitly install the version you want with tox?

**Comment by carltongibson** [comment]
OK. Thanks for the work. I will have a look later. (First glance... 🤔)


(Aside: do you use bootstrap4? There a a few small template issues there, but I don't use it, and don't have the time to dive into it, so they're not getting any love...)

**Comment by johnthagen** [comment]
> Aside: do you use bootstrap4? 

I don't, no. I use `django-crispy-forms` transitively through some other dependencies rather than directly. So I don't really know anything about the internals of `crispy-forms`, just about overall Django/Python testing/CI like I contributed with this PR.

**Comment by carltongibson** [comment]
OK. No stress. (I’m just on the lookout for someone using crispy that also uses BS4 to help me. It’s just templates. Nothing internal.)

Thanks for the input!

**Comment by johnthagen** [comment]
Looks like @voidus fixed the tests in #877

**Comment by carltongibson** [comment]
Superceded by  #877. Thanks for the effort @johnthagen!

**Pull request closed without merging**
