### PR TITLE
Custom file input field for Bootstrap 4

### PR DESCRIPTION
**Pull request by fabianallendorf**
### Why merge this PR?
The Issue #734 suggested to add custom file input for Bootstrap 4.

### Description
A new layout template called `file_input.html` was created which holds the HTML of the Bootstrap4 [custom file input](https://getbootstrap.com/docs/4.0/components/input-group/#custom-file-input)
A distinction was included in `field.html` which checks if the field to render is a file input field using `is_file`.
The classes `form-control` and `is-invalid` are added to the field input in order to show form errors for the field.

### CODE REVIEW

**Comment by zoidbergwill** [comment]
Yay, a first-time contributor. 🎉 

Congratulations and thank you for your contribution, this looks great. Just gonna give it a test and then will merge it, since it looks good to me! :+1:

**Comment by zoidbergwill** [comment]
Works perfectly, and looks much better. ✨

**Comment by kantmichel** [comment]
Any time this will be implemented? Right now the file upload is blanking/not showing at all.when using standard implementation.

**Comment by rafiqhilali** [comment]
I've been playing around with this, it may be worth adding to the docs that unless you add some custom JS, the label that says 'Choose File' will not update on choosing a file, leading to a slightly odd UI.

I added (using JQuery)
```javascript
const fileInput = $('#id_of_file_input');
  fileInput.change(function() {
    let fileName = fileInput.val();
    fileName = fileName.replace(/^.*[\\\/]/, '');
    fileInput.next('.custom-file-label').html(fileName);
  });

**Pull request merged**
