### PR TITLE
Fixed unexpected addition the 'active' css_class to AccordionGroup 

### PR DESCRIPTION
**Pull request by kosdmit**
issue #1395

This PR is aimed to fix a complex issue in several template packs:
[crispy-bootstrap3](https://github.com/django-crispy-forms/crispy-bootstrap3/issues/9)
[crispy-bootstrap4](https://github.com/django-crispy-forms/crispy-bootstrap4/issues/27)
[crispy-bootstrap5](https://github.com/django-crispy-forms/crispy-bootstrap5/issues/168)

As you can see [here](https://github.com/django-crispy-forms/crispy-bootstrap5/pull/180) these issues have not been resolved for the following reason:
the existing rendering procedure adds 'active' class to css_class string,  causing tests crash.

I've moved the render() method from Container to Tab (with according to @smithdc1 [proposal](https://github.com/django-crispy-forms/crispy-bootstrap5/pull/180#issuecomment-2214925672)), and now AccordionGroup doesn't have 'active' class with according to bootstrap docs.

I've also added temporary test that uses fixed templates to check is all ok :)

### CODE REVIEW

**Comment by kosdmit** [comment]
Hello, @django-crispy-forms team

When you check it out and if you give a positive feedback, I think I should add a commit in this pull request that removes temporary templates and move the new test to template packs repositories. That will get rid of TODOs in the project.

**Comment by smithdc1** [comment]
I've started to review this. A couple of initial comments.

> add a commit in this pull request that removes ...

Please can you add another commit for this?

Also -- could you add an entry for this to the changelog?

**Comment by kosdmit** [comment]
> Please can you add another commit for this?

I've added a revert commit to do that, did i understand you right?

**Comment by smithdc1** [comment]
Thanks @kosdmit this looks good to me -- I'll work on a release which I think will help make the changes in the template packs.

**Pull request merged**
