### PR TITLE
Updated suported python versions in classifiers

### PR DESCRIPTION
**Pull request by michael-k**

### CODE REVIEW

**Comment by zoidbergwill** [comment]
We're testing against more version in [Travis](https://github.com/django-crispy-forms/django-crispy-forms/blob/dev/.travis.yml), but I think this is still a great improvement and more accurate. :+1:

LGTM. Thanks for your contribution.

**Comment by michael-k** [comment]
The only difference is python 3.2 and that reached its EOL in February 2016: https://www.python.org/dev/peps/pep-0392/#lifespan

**Comment by zoidbergwill** [comment]
Yeah, think we can happily get rid of it then too.

**Comment by michael-k** [comment]
see #730

**Pull request merged**
