### PR TITLE
Fix non-HTTPS resources

### PR DESCRIPTION
**Pull request by zoidbergwill**
Closes https://github.com/django-crispy-forms/django-crispy-forms/issues/850

I might be missing some.

The two in the reported issue are fixed.

### CODE REVIEW

**Comment by zoidbergwill** [comment]
The test failures look unrelated, but I'll take a look at them in the morning.

**Comment by bryan-brancotte** [comment]
Hi @carltongibson a little up on this PR as it seems to fix the ci

**Comment by carltongibson** [comment]
Hi @bryan-brancotte. Fancy pressing "Squash and merge"? 🙂

**Comment by bryan-brancotte** [comment]
Hi @carltongibson yes i would want to :) But I thought you  wanted to do some changes following your review.

**Pull request merged**
