### PR TITLE
Fix css_id for non-ASCII characters - allow unicode in slugify function

### PR DESCRIPTION
**Pull request by izabelakowal**
I've been working on a project that is translated into multiple languages. The bootstrap accordion groups haven't been functioning properly while the container name was translated to Japanese. I realized that the `css_id` of the container is slugified while allowing only ASCII characters.

### CODE REVIEW

**Comment by izabelakowal** [comment]
Fixed the isort issue.

**Comment by smithdc1** [comment]
Thanks for the PR.

Do you think you could add a test for this?

**Comment by izabelakowal** [comment]
@smithdc1 test case added.

**Review by smithdc1 — APPROVED** [review]
Thanks for the patch. 👍

**Pull request closed without merging**
