### PR TITLE
Test against 3.12-dev & add Python 3.12 classifier

### PR DESCRIPTION
**Pull request by foarsitter**
Ran the tests against 3.12-dev and they succeed. Good job everybody! 

I didn't added 3.12 to the publish version matrix since 3.12 better may not block an upcoming release.

### CODE REVIEW

**Comment by foarsitter** [comment]
> 
> I think let's add it. Better do it now than forget later.

Alright, pushed.

**Comment by smithdc1** [comment]
Great. 👍

Could you add a small note to the changelog?

**Comment by foarsitter** [comment]
Of course, done!

**Comment by smithdc1** [comment]
Thank you for the contributions!

**Pull request merged**
