### PR TITLE
Support for new Bootstrap4 alpha5 markup

### PR DESCRIPTION
**Pull request by darklow**
I haven't checked 100% all bootstrap markup yet, but 4x main changes I mentioned in my issue #658 post are ready. Let's me know what you think. We can also discuss checkbox double label issue before closing PR.

### CODE REVIEW

**Comment by darklow** [comment]
I am not proud of this conditional check that are in few templates:
```
<div class="form-group{% if not form_class or 'form-inline' not in form_class %} row{% endif %}">
```

Thing is - for inline forms we need just `.form-group` class, but for non-inline forms we need to use it together with `.row` and currently only difference is in form_class variable. Let me know if you want me to add template filter maybe or even global context variable {{ has_inline_class }}?
```
form-group {%if form_class|has_inline_class %}...
```

**Comment by darklow** [comment]
I will add some more markup updates in nearest time.

**Comment by zoidbergwill** [comment]
@darklow Thanks for this PR. I'll take a look at it this week.

**Comment by auvipy** [comment]
alphha6 is released http://blog.getbootstrap.com/2017/01/06/bootstrap-4-alpha-6/ next is beta1 could you update the pr with that?

**Comment by carltongibson** [comment]
@darklow Any chance you could update this to latest `dev`? Thanks!

**Comment by carltongibson** [comment]
Also, can you look at #676? — it's only a one liner so could easily be handled here. (Maybe it already is?)

Thanks.

**Comment by darklow** [comment]
I think we should wait BS4 final, it just too much refactoring on each new alpha. In the meanwhile feel free to copy edited templates from this PR to your own template directory and adjust if needed.

**Comment by zoidbergwill** [comment]
Definitely a bunch of work to keep up with bootstrap v4 alpha/beta. And now there are conflicts. Hopefully will get to take a look at this properly in the next month or two.

**Comment by carltongibson** [comment]
See #732: I've asked for help finalising Bootstrap 4 support, and we'll do a new release in the autumn before Django 2.0, or sooner if we get lots of input.

BS4 is now "Beta" and should be stable enough. If this PR can be updated for that we'd be glad to have it! Ta!

**Comment by zoidbergwill** [comment]
I've put these changes into my PR: https://github.com/django-crispy-forms/django-crispy-forms/pull/735

**Pull request closed without merging**
