### PR TITLE
Using is-valid css class with bootstrap 4

### PR DESCRIPTION
**Pull request by bryan-brancotte**

### CODE REVIEW

**Comment by carltongibson** [comment]
Hi @bryan-brancotte. I've rebased this on `master` after #893, to avoid the merge commits. 🤞 should resolve the build issue.

**Comment by carltongibson** [comment]
Hey @bryan-brancotte. Looks good. If you're happy with this, _Squash and Merge_ 🎉

**Comment by bryan-brancotte** [comment]
Good news ! So no need to add tests to ensure that each element of rendered layout is in the right order ?

**Comment by carltongibson** [comment]
Up to you. 

For tests: am I trying to work out how to do something? Is it likely to be wrong? Is it a regression (I.e. a bug)? Is a future change likely to break it? 

For templates, sometimes it’s just not worth testing: did you type it right? If so, what are you testing? (That the template system works...?)

If there’s questionable logic, that could be wrong, then a small test is justified. 

So I’ll let you decide.

**Pull request merged**
