### PR TITLE
File field Bootstrap4: avoids long file names overflowing outside the…

### PR DESCRIPTION
**Pull request by cpina**
… label

### CODE REVIEW

**Comment by cpina** [comment]
This helps the overflow problem. I haven't updated the unit tests but I can do it if we decide that this is the right solution. I'm usually on the backend side and my CSS is usually copy-paste, and I haven't investigated the best way to do this on django-crispy-fields. So feel free to suggest other solutions. The bottom one is not perfect but better than now in my opinion.

Before:
before

After:
after

@smithdc1 and @bryan-brancotte: any thoughts welcome!

**Comment by smithdc1** [comment]
Thanks for this. 

I've got a busy week ahead so will probably be next week before I get chance to look at this. 

Agree your image looking better.

**Comment by smithdc1** [comment]
Hi @cpina @bryan-brancotte 

Just having a look at this and I have a couple of questions (maybe I'm looking at it wrong?)

1) The clear box seems to have drifted left?
image

2) I was expecting to see the file name chopped?
image

**Comment by bryan-brancotte** [comment]
Hi @smithdc1 

1. You are looking at it right, I mistakenly removed ``flex-grow: 1;``. It has been re-added.

2. The file is chopped, but as BS4 user :after to show "Browse", the chopping and the ... are behind the Browse... at least nothing is overflowing.

**Review by smithdc1 — APPROVED** [review]

**Comment by smithdc1** [comment]
This looks good to me.

@cpina  does this work for you as well?

**Comment by cpina** [comment]
Hi @smithdc1  - In the project that I work for it looks very good (so, for me, it can be merged :-) ):
django-crispy-forms-01
django-crispy-forms-02
django-crispy-forms-03
django-crispy-forms-04

This is using `-e git://github.com/cpina/django-crispy-forms.git@9e030b1a67e7ff9c6401bb8356a13893bee6464b#egg=django_crispy_forms`

I've had a quick look at `crispy-test-project` and all good as well.

My screenshots are taken from a Firefox 77.0.1 on Linux. Using Chromium the project that I work for looks good as well.

**Comment by smithdc1** [comment]
Thanks all 👏

**Comment by cpina** [comment]
Thanks very @bryan-brancotte :+1:  and @smithdc1 :+1:

**Pull request merged**
