### PR TITLE
Apply Black to entire codebase

### PR DESCRIPTION
**Pull request by smithdc1**
2nd attempt at this :-)

Putting this out for discussion - is this something that we want to do? Appreciate Black is still in beta....

Files that I have changed are:
setup.cfg : changed flake8 settings to match black docs
readme.rst : added black badge
pyproject.toml : added black settings

Note: I didn't add black to requirements.txt as it doesn't work on py35 & therefore causes CI tests to fail.

If implemented I would then look at introducing black style checking in flake8.

### CODE REVIEW

**Comment by carltongibson** [comment]
That´s quite exciting. 🕺

**Comment by smithdc1** [comment]
Yes. This next release (1.9) will have a lot of code changes but much of will be behind the scenes work rather than new features for users. Hopefully it will help maintenance of the project going forward. 

I was nervous pressing merge on this one given the amount of lines of code it impacts. But this is nothing compared to applying it to applying it all of Django; when the time comes!

**Comment by carltongibson** [comment]
Indeed. I’m letting someone else do that. 😀

**Comment by smithdc1** [comment]
😄 

May be worth giving some warning that this it is coming (at the right time). Re-basing existing PR on top of the applying Black commit is a bit painful. It may be in this case I'd have been best re-basing some of the other PRs first....

**Comment by carltongibson** [comment]
There aren’t so many. It’ll be Ok

**Pull request merged**
